# Test your FastAPI endpoints

GET http://127.0.0.1:8080/
Accept: application/json
###

GET http://127.0.0.1:8000/hello/User
Accept: application/json
###


POST http://localhost:8000/order
Content-Type: application/json

{
    "order_items": [
      {
        "product_type_id": "643b21db76cdab22716407ad",
        "qty": 5
      }
    ],
    "date_ordered": "2008-09-15T15:53:00+05:00"
}
###

GET http://localhost:8000/dashboard/heatmap
